use_frameworks!

target 'JTSLocalizable_Example' do
  pod 'JTSLocalizable', :path => '../'
  pod 'AFNetworking', '~> 3.2.1'

  target 'JTSLocalizable_Tests' do
    inherit! :search_paths

    
  end
end
